/*
 *    GeoTools - The Open Source Java GIS Toolkit
 *    http://geotools.org
 *
 *    (C) 2014, Open Source Geospatial Foundation (OSGeo)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotools.process.spatialstatistics;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.geotools.data.simple.SimpleFeatureCollection;
import org.geotools.process.Process;
import org.geotools.process.ProcessException;
import org.geotools.process.ProcessFactory;
import org.geotools.process.spatialstatistics.core.Params;
import org.geotools.process.spatialstatistics.transformation.ExplodeFeatureCollection;
import org.geotools.text.Text;
import org.geotools.util.NullProgressListener;
import org.geotools.util.logging.Logging;
import org.opengis.util.ProgressListener;

import com.vividsolutions.jts.geom.Coordinate;
import com.vividsolutions.jts.geom.Geometry;
import com.vividsolutions.jts.geom.GeometryFactory;
import com.vividsolutions.jts.geom.LineString;
import com.vividsolutions.jts.geom.LinearRing;
import com.vividsolutions.jts.geom.MultiPolygon;
import com.vividsolutions.jts.geom.Polygon;

/**
 * Creates a singlepart features generated by separating multipart input features.
 * 
 * @author Minpa Lee, MangoSystem
 * 
 * @source $URL$
 */
public class MultipartToSinglepartProcess extends AbstractStatisticsProcess {
    protected static final Logger LOGGER = Logging.getLogger(MultipartToSinglepartProcess.class);

    private boolean started = false;

    public MultipartToSinglepartProcess(ProcessFactory factory) {
        super(factory);
    }

    public ProcessFactory getFactory() {
        return factory;
    }

    public static SimpleFeatureCollection process(SimpleFeatureCollection inputFeatures,
            ProgressListener monitor) {
        Map<String, Object> map = new HashMap<String, Object>();
        map.put(MultipartToSinglepartProcessFactory.inputFeatures.key, inputFeatures);

        Process process = new MultipartToSinglepartProcess(null);
        Map<String, Object> resultMap;
        try {
            resultMap = process.execute(map, monitor);
            return (SimpleFeatureCollection) resultMap
                    .get(MultipartToSinglepartProcessFactory.RESULT.key);
        } catch (ProcessException e) {
            LOGGER.log(Level.FINER, e.getMessage(), e);
        }

        return null;
    }

    @Override
    public Map<String, Object> execute(Map<String, Object> input, ProgressListener monitor)
            throws ProcessException {
        if (started)
            throw new IllegalStateException("Process can only be run once");
        started = true;

        if (monitor == null)
            monitor = new NullProgressListener();
        try {
            monitor.started();
            monitor.setTask(Text.text("Grabbing arguments"));
            monitor.progress(10.0f);

            SimpleFeatureCollection inputFeatures = (SimpleFeatureCollection) Params.getValue(
                    input, MultipartToSinglepartProcessFactory.inputFeatures, null);
            if (inputFeatures == null) {
                throw new NullPointerException("inputFeatures parameters required");
            }

            monitor.setTask(Text.text("Processing ..."));
            monitor.progress(25.0f);

            if (monitor.isCanceled()) {
                return null; // user has canceled this operation
            }

            // start process
            SimpleFeatureCollection resultFc = new ExplodeFeatureCollection(inputFeatures);
            // end process

            monitor.setTask(Text.text("Encoding result"));
            monitor.progress(90.0f);

            Map<String, Object> resultMap = new HashMap<String, Object>();
            resultMap.put(MultipartToSinglepartProcessFactory.RESULT.key, resultFc);
            monitor.complete(); // same as 100.0f

            return resultMap;
        } catch (Exception eek) {
            monitor.exceptionOccurred(eek);
            return null;
        } finally {
            monitor.dispose();
        }
    }

    private Geometry removeHoles(Geometry inputPolygon) {
        Class<?> geomBinding = inputPolygon.getClass();
        GeometryFactory factory = inputPolygon.getFactory();

        Geometry finalGeom = inputPolygon;
        if (Polygon.class.equals(geomBinding)) {
            finalGeom = removeHoles((Polygon) inputPolygon);
        } else if (MultiPolygon.class.equals(geomBinding)) {
            List<Polygon> polygons = new ArrayList<Polygon>();
            for (int index = 0; index < inputPolygon.getNumGeometries(); index++) {
                Polygon polygon = (Polygon) inputPolygon.getGeometryN(index);
                polygons.add((Polygon) removeHoles(polygon));
            }
            finalGeom = factory.createMultiPolygon(GeometryFactory.toPolygonArray(polygons));
            finalGeom.setUserData(inputPolygon.getUserData());
        }
        return finalGeom;
    }

    private Geometry removeHoles(Polygon polygon) {
        GeometryFactory factory = polygon.getFactory();
        LineString exteriorRing = polygon.getExteriorRing();

        // check exterior ring
        if (!exteriorRing.isRing()) {
            List<Coordinate> coordList = Arrays.asList(exteriorRing.getCoordinates());
            coordList.add(exteriorRing.getStartPoint().getCoordinate());

            Coordinate[] coords = new Coordinate[coordList.size()];
            coordList.toArray(coords);
            exteriorRing = factory.createLinearRing(coords);
        }

        Geometry finalGeom = factory.createPolygon((LinearRing) exteriorRing, null);
        finalGeom.setUserData(polygon.getUserData());
        return finalGeom;
    }
}
