/*
 *    GeoTools - The Open Source Java GIS Toolkit
 *    http://geotools.org
 *
 *    (C) 2014, Open Source Geospatial Foundation (OSGeo)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotools.process.spatialstatistics;

import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.geotools.data.simple.SimpleFeatureCollection;
import org.geotools.process.Process;
import org.geotools.process.ProcessException;
import org.geotools.process.ProcessFactory;
import org.geotools.process.spatialstatistics.core.Params;
import org.geotools.process.spatialstatistics.transformation.MultipartFeatureCollection;
import org.geotools.util.logging.Logging;
import org.opengis.util.ProgressListener;

/**
 * Creates a multipart features generated by grouping singlepart input features.
 * 
 * @author Minpa Lee, MangoSystem
 * 
 * @source $URL$
 */
public class SinglepartToMultipartProcess extends AbstractStatisticsProcess {
    protected static final Logger LOGGER = Logging.getLogger(SinglepartToMultipartProcess.class);

    private boolean started = false;

    public SinglepartToMultipartProcess(ProcessFactory factory) {
        super(factory);
    }

    public ProcessFactory getFactory() {
        return factory;
    }

    public static SimpleFeatureCollection process(SimpleFeatureCollection inputFeatures,
            String caseField, Boolean dissolve, ProgressListener monitor) {
        Map<String, Object> map = new HashMap<String, Object>();
        map.put(SinglepartToMultipartProcessFactory.inputFeatures.key, inputFeatures);
        map.put(SinglepartToMultipartProcessFactory.caseField.key, caseField);
        map.put(SinglepartToMultipartProcessFactory.dissolve.key, dissolve);

        Process process = new SinglepartToMultipartProcess(null);
        Map<String, Object> resultMap;
        try {
            resultMap = process.execute(map, monitor);

            return (SimpleFeatureCollection) resultMap
                    .get(SinglepartToMultipartProcessFactory.RESULT.key);
        } catch (ProcessException e) {
            LOGGER.log(Level.FINER, e.getMessage(), e);
        }

        return null;
    }

    @Override
    public Map<String, Object> execute(Map<String, Object> input, ProgressListener monitor)
            throws ProcessException {
        if (started)
            throw new IllegalStateException("Process can only be run once");
        started = true;

        try {
            SimpleFeatureCollection inputFeatures = (SimpleFeatureCollection) Params.getValue(
                    input, SinglepartToMultipartProcessFactory.inputFeatures, null);

            String caseField = (String) Params.getValue(input,
                    SinglepartToMultipartProcessFactory.caseField,
                    SinglepartToMultipartProcessFactory.caseField.sample);
            if (inputFeatures == null || caseField == null || caseField.trim().length() == 0) {
                throw new NullPointerException("inputFeatures, caseField, parameters required");
            }

            Boolean dissolve = (Boolean) Params.getValue(input,
                    SinglepartToMultipartProcessFactory.dissolve,
                    SinglepartToMultipartProcessFactory.dissolve.sample);

            // start process
            SimpleFeatureCollection resultFc = new MultipartFeatureCollection(inputFeatures,
                    caseField, dissolve);
            // end process

            Map<String, Object> resultMap = new HashMap<String, Object>();
            resultMap.put(SinglepartToMultipartProcessFactory.RESULT.key, resultFc);
            return resultMap;
        } catch (Exception eek) {
            throw new ProcessException(eek);
        } finally {
            started = false;
        }
    }
}
